### ISSUE TITLE
Game will crash when you open some creatures info window

### ISSUE THREAD

**Issue by lishaoxia1985** [vcmi-mods/horn-of-the-abyss#118]
The creatures contain these:
Automatons, Dreadnoughts, Ayssids, Haspids. I have not tested all of the creatues.

**Comment by Laserlicht** [comment]
Not able to reproduce on PC, only on android. What version you're testing?

@IvanSavenko Any idea how to debug? Or what's the reason? Happens only on creatures with missing bonus symbol.

**Comment by IvanSavenko** [comment]
Can you show call stack of the crash? This sounds vaguely familiar...

**Comment by Laserlicht** [comment]
> Can you show call stack of the crash? This sounds vaguely familiar...

I don't have a callstack on android. :D
Or is it in any logs?

**Comment by IvanSavenko** [comment]
Ah, Android only.
Well, in theory you can try to get call stack using ADB - should be visible in log from what I remember.

Also - try both debug & release builds on your system. Release-only crashes might happen due to uninitialized memory. So if this is the reason then release build might also crash on your system

**Comment by Laserlicht** [comment]
Tested it on gcc-debug and clang-release. Not reproducible for me.

Also no ADB running yet. :(

**Comment by IvanSavenko** [comment]
Reproduced on PC. Happens only if xbrz is active. Will fix.

**Comment by Laserlicht** [comment]
> Reproduced on PC. Happens only if xbrz is active. Will fix.

Nice find, yeah - have xbrz enabled on mobile. :)
